
COMPOUND_TO_SMILES = {
    'Dopamine': 'NCCc1ccc(O)c(O)c1',
    'Methamphetamine': 'CNC(C)Cc1ccccc1',
    'Ritalin': 'COC(=O)C(c1ccccc1)C1CCCCN1',
    'Phenibut': 'NCC(CC(=O)O)c1ccccc1',
    'Aspirin': 'CC(=O)Oc1ccccc1C(=O)O',
    'Phenyltriazine': 'Cc1nnncc1-c1ccccc1',
    'Amphetamine': 'CC(N)Cc1ccccc1',
    'Wellbutrin': 'CC(NC(C)(C)C)C(=O)c1cccc(Cl)c1',
    'Mdma': 'CNC(Cc1ccc2c(c1)OCO2)C',
    'Cathinone': 'CC(N)C(=O)c1ccccc1',
    'Fluoxetine': 'CNCCC(Oc1ccc(C(F)(F)F)cc1)c1ccccc1',
    'Gaba': 'NCCCC(=O)O',
    'Gabapentin': 'NCC1(CC(=O)O)CCCCC1',
    'Pregabalin': 'CC(C)CC(CN)CC(=O)O',
    'Serotonin': 'NCCc1c[nH]c2ccc(O)cc12',
    'Psilocybine': 'CN(C)CCc1c[nH]c2cccc(OP(=O)(O)O)c12',
    'Mescaline': 'COc1cc(CCN)cc(OC)c1OC',
    'Ibuprofen': 'CC(C)Cc1ccc(C(C)C(=O)O)cc1',
    'Acetaminophen': 'CC(=O)Nc1ccc(O)cc1',
    'Diclofenac': 'O=C(O)Cc1ccccc1Nc1c(Cl)cccc1Cl',
    'Niacin': 'O=C(O)c1cccnc1',
    'Retinol': 'CC(C=CC1=C(C)CCCC1(C)C)=CC=CC(C)=CCO',
    'Fentanyl': 'CCC(=O)N(c1ccccc1)C1CCN(CCc2ccccc2)CC1',
    'Tramadol': 'COc1cccc(C2(O)CCCCC2CN(C)C)c1',
    'Methadone': 'CCC(=O)C(CC(C)N(C)C)(c1ccccc1)c1ccccc1',
    'Lamotrigine': 'Nc1nnc(-c2cccc(Cl)c2Cl)c(N)n1',
    'Ketamine': 'CNC1(c2ccccc2Cl)CCCCC1=O',
    'Modafinil': 'NC(=O)CS(=O)C(c1ccccc1)c1ccccc1',
    'Propofol': 'CC(C)c1cccc(C(C)C)c1O',
    'Propranolol': 'CC(C)NCC(O)COc1cccc2ccccc12',
    'Brivaracetam': 'CCCC1CC(=O)N(C(CC)C(N)=O)C1',
    'Piracetam': 'NC(=O)CN1CCCC1=O',
    'Lisdexamfetamine': 'CC(Cc1ccccc1)NC(=O)C(N)CCCCN',
    'Naproxen': 'COc1ccc2cc(C(C)C(=O)O)ccc2c1',
    'Epinephrine': 'CNCC(O)c1ccc(O)c(O)c1',
    'Caffeine': 'Cn1c(=O)c2c(ncn2C)n(C)c1=O',
    'Diphenylamine': 'c1ccc(Nc2ccccc2)cc1',
    'Pramiracetam': 'CC(C)N(CCNC(=O)CN1CCCC1=O)C(C)C',
    'Benzocaine': 'CCOC(=O)c1ccc(N)cc1',
    'Valproic acid': 'CCCC(CCC)C(=O)O',
    'Diphenyl methane': 'c1ccc(Cc2ccccc2)cc1',
    'Pyridoxine': 'Cc1ncc(CO)c(CO)c1O',
    'Lysine': 'C(CCN)CC(C(=O)O)N',
    'Oxiracetam': 'NC(=O)CN1CC(O)CC1=O',
    'Phenylpiracetam': 'NC(=O)CN1CC(c2ccccc2)CC1=O',
    'Phenylpiracetam Hydrazide': 'NNC(=O)CN1CC(c2ccccc2)CC1=O',
    'Aniracetam': 'COc1ccc(C(=O)N2CCCC2=O)cc1',
    'Seletracetam': 'CCC(C(N)=O)N1CC(C=C(F)F)CC1=O',
    'Levetiracetam': 'CCC(C(N)=O)N1CCCC1=O',
    'Fasoracetam': 'O=C1CCC(C(=O)N2CCCCC2)N1',
    'Methylphenidate': 'COC(=O)C(c1ccccc1)C1CCCCN1',
    'Methcathinone': 'CNC(C)C(=O)c1ccccc1',
    'Pyrovalerone': 'CCCC(C(=O)c1ccc(C)cc1)N1CCCC1',
    'Mephedrone': 'CNC(C)C(=O)c1ccc(C)cc1',
    'Bufotenine': 'CN(C)CCc1c[nH]c2ccc(O)cc12',
    'Bupropion': 'CC(NC(C)(C)C)C(=O)c1cccc(Cl)c1',
    'Dimethyltryptamine': 'CN(C)CCc1c[nH]c2ccccc12',
    '5-Hydroxytryptophan': 'NC(Cc1c[nH]c2ccc(O)cc12)C(=O)O',
    'Tryptophan': 'NC(Cc1c[nH]c2ccccc12)C(=O)O',
    '5-MeO-DIPT': 'COc1ccc2[nH]cc(CCN(C(C)C)C(C)C)c2c1',
    '5-MeO-DMT': 'COc1ccc2[nH]cc(CCN(C)C)c2c1',
    'Indole-3-acetic acid': 'O=C(O)Cc1c[nH]c2ccccc12',
    'Melatonin': 'COc1ccc2[nH]cc(CCNC(C)=O)c2c1',
    'Psilocin': 'CN(C)CCc1c[nH]c2cccc(O)c12',
    'MDMA': 'CNC(C)Cc1ccc2c(c1)OCO2',
    'Meperidine': 'CCOC(=O)C1(c2ccccc2)CCN(C)CC1',
    'Tapentadol': 'CCC(c1cccc(O)c1)C(C)CN(C)C',
    'Phencyclidine': 'c1ccc(C2(N3CCCCC3)CCCCC2)cc1',
    'Methoxetamine': 'CCNC1(c2cccc(OC)c2)CCCCC1=O',
    '4-(Dimethylamino)-4-(p-tolyl)cyclohexanone': 'Cc1ccc(C2(N(C)C)CCC(=O)CC2)cc1',
    'Tiletamine': 'CCNC1(c2cccs2)CCCCC1=O',
    'GABA': 'NCCCC(=O)O',
    'Nipecotic acid': 'O=C(O)C1CCCNC1',
    'Baclofen': 'NCC(CC(=O)O)c1ccc(Cl)cc1',
    'Atomoxetine': 'CNCCC(Oc1ccccc1C)c1ccccc1',
    'Tyrosine': 'NC(Cc1ccc(O)cc1)C(=O)O',
    'Nisoxetine': 'CNCCC(Oc1ccccc1OC)c1ccccc1',
    'Pivagabine': 'CC(C)(C)C(=O)NCCCC(=O)O',
    'Phentermine': 'CC(C)(N)Cc1ccccc1',
    'Prolintane': 'CCCC(Cc1ccccc1)N1CCCC1',
    'Methylone': 'CNC(C)C(=O)c1ccc2c(c1)OCO2',
    'Sildenafil': 'CCCc1nn(C)c2c(=O)[nH]c(-c3cc(S(=O)(=O)N4CCN(C)CC4)ccc3OCC)nc12',
    'Tadalafil': 'CN1CC(=O)N2C(Cc3c([nH]c4ccccc34)C2c2ccc3c(c2)OCO3)C1=O',
    'Menthol': 'CC1CCC(C(C)C)C(O)C1',
    'Camphor': 'CC12CCC(CC1=O)C2(C)C',
    }


